### ISSUE TITLE
Henry, Please.

### ISSUE THREAD

**Issue by pleasehenry** [henry7720/2048-Cupcakes#2]
Dear Mr. Henry,

I began my year playing your cupcake game. It was a long awaited journey to the Christmas Cupcake. Once I achieved this and saw the beautiful Christmas Cupcake, I was overjoyed. I struggled for weeks and weeks anticipating what was next after the Christmas Cupcake. I even wondered if it would change for the next holiday. Henry, you can imagine my surprise when I combined two Christmas Cupcakes and found that there was in fact no bigger cupcake. Just a blank screen. I'm disappointed. Now, I did some research, and I found that you have not updated the game for 4 years!!! WTH!!! My year is ruined. Everything I've worked up to now seems useless. Henry, please, if you are out there, come back. Update the cupcakes. Give us bigger cupcakes. Do it for your loyal followers. Or else... I may just have to find a new game. Please Henry, please.

Sincerely,
A disappointed loyal fan.

**Comment by pleasehenry** [comment]
henryyyyy whereeee reee youuuuuuuwehf uyw

**Comment by pleasehenry** [comment]
henry, it has been almost two weeks since my previous message. please for the love of god answer me

**Comment by floppatschool** [comment]
henry please
